language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.0.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.1
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.1.2
  - OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.2
  - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0